import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootProvider from '@/utils/recoilRootProvider'
import ReactQueryProviders from '@/utils/reactQuaryRootprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <RecoilRootProvider>{children}</RecoilRootProvider>
        </ReactQueryProviders>
      </body>
    </html>
  )
}

export default RootLayout
